### ISSUE TITLE
unable to start backend-redis container

### ISSUE THREAD

**Issue by cplewis** [gpe-mw-training/3scale_onpremise_implementation_labs#1]
I pulled the latest version of this lab resource this morning and started from scratch. At step 5 (Resume Deployments), I am hitting a problem with the redis container. 

jboss@rhtapimgmt ~/lab/3scale_onpremise_implementation_labs (master *) $ oc get pvc
NAME                    STATUS    VOLUME    CAPACITY   ACCESSMODES   AGE
backend-redis-storage   Bound     vol53     4Gi        RWO           <invalid>
mysql-storage           Bound     vol29     4Gi        RWO           <invalid>
system-redis-storage    Bound     vol67     4Gi        RWO           <invalid>
system-storage          Bound     vol154    4Gi        RWO,RWX       <invalid>

jboss@rhtapimgmt ~/lab/3scale_onpremise_implementation_labs (master *) $ oc get pods
NAME                      READY     STATUS    RESTARTS   AGE
**backend-redis-1-deploy    0/1       Error     0          <invalid>**
system-memcache-1-xg6tt   1/1       Running   0          <invalid>
system-mysql-1-l73tv      1/1       Running   0          <invalid>
system-redis-1-deploy     0/1       Error     0          <invalid>
zync-database-1-v9d4c     1/1       Running   0          <invalid>

2017-11-18 08:42:10 -0500 EST   2017-11-18 08:32:11 -0500 EST   45        backend-redis-1-17x42    Pod                                                      Warning   FailedSync          {kubelet node1.na1.internal}     Error syncing pod, skipping: failed to "StartContainer" for "backend-redis" with RunContainerError: "GenerateRunContainerOptions: mkdir /var/lib/origin/openshift.local.volumes/pods/e07d4a7b-cc64-11e7-aae0-0682973451aa/volumes/kubernetes.io~configmap/redis-config/redis.conf: not a directory"

[redis-container-fail.log](https://github.com/gpe-mw-training/3scale_onpremise_implementation_labs/files/1484657/redis-container-fail.log)

**Comment by cplewis** [comment]
I think it's related to permissions. I was able to set the volume to /tmp and the pod starts up and correctly places the redis.conf file at /tmp/redis.conf. Looking at permissions on /tmp and /etc, 

```
> 8 drwxr-xr-x.  51 root root       4096 Nov 18 18:54 etc
> 0 drwxrwsrwx.   3 root 1000140000   79 Nov 18 18:54 tmp
```

**Comment by jbride** [comment]
the redis pod is known to start up fine on OCP 3.5.5.31 .
Some other versions of OCP are known to be problematic with the redis configs of 3scale.
What version of OCP are you are working on ?

**Comment by cplewis** [comment]
I was running the version automatically provisioned by the elab, v3.5.5.31 
It appears to be fixed now as I was able to deploy the redis container.
